platform :ios,'7.0'
use_frameworks!

target 'AFNetworking3-RACExtensions_Example' do
  pod 'AFNetworking3-RACExtensions', :path => '../'

  target 'AFNetworking3-RACExtensions_Tests' do
    inherit! :search_paths
  end
end
